### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by RenatoAugustoIairFigueroaMayta** [EnhancedNetwork/TownofHost-Enhanced#1223]
HELLO, do you know any mod if this mod also detects those who use cheats?

**Comment by NikoCat233** [comment]
Check BetterAmongUs or go to a anticheat custom server

**Comment by RenatoAugustoIairFigueroaMayta** [comment]
When I click on betterAmonUs on discord it takes me to his discord, or what channel is it bro? Help me

**Comment by NikoCat233** [comment]
I think you can ask on discord instead of putting issues here
