### ISSUE TITLE
A ERROR

### ISSUE THREAD

**Issue by cxleiaaa2** [EnhancedNetwork/TownofHost-Enhanced#1257]
Original Poster: Discord Tag (moe.dev)
Version: latest
Original Date of Issue: (Date) 2024/10/6
Logs Attached? 
Fix Attempted Before? Yes/No
Map: All

**Comment by cxleiaaa2** [comment]
[TOHE-v2024.0813.203.9999-2024-10-06_14.45.11.log](https://github.com/user-attachments/files/17275547/TOHE-v2024.0813.203.9999-2024-10-06_14.45.11.log)

**Comment by NikoCat233** [comment]
what error btw

**Comment by NikoCat233** [comment]
此问题已经在210canary中修复
This problem has already been fixed in 210 beta1 release
