### ISSUE TITLE
Host banned for Cheating? 

### ISSUE THREAD

**Issue by Villagerzock** [EnhancedNetwork/TownofHost-Enhanced#1288]
i get instabanned from my lobby when trying to create a game
these are the logs for the ban

[Warning:      TOHE] [18:40:57][<>c.<Postfix>b__0_0(BanManager.cs:230)][CheckEACList]friendcode : spaperfect#5939, hashedPUID :  banned by EAC reason : Came into server looking for hacks, sent friend code
[Info   :      TOHE] [18:40:57][Reason Disconnect]Disconnect (Reason:Banned:, ping:0)

**Comment by redphantom1000** [comment]
this is a known issue. 
![see this screenshot](https://github.com/user-attachments/assets/17f445af-9b62-47ec-9f78-1ff644b04b8a)

**Comment by Villagerzock** [comment]
thanks
