### ISSUE TITLE
Pursuer can "Kill" Hawk

### ISSUE THREAD

**Issue by BatmenzDW** [EnhancedNetwork/TownofHost-Enhanced#1330]
Original Poster: Batmenz
    Version: 2.1.1
    Original Date of Issue: December 22, 2024
    Logs Attached? [Pastebin](https://pastebin.com/uv0Nbt6X)
    Reproducible? Have not attempted
    Description/Additional Notes: Pursuer uses ability on crew who becomes hawk. Hawk tries to kill someone, they "die" to misfire.

**Comment by NikoCat233** [comment]
your pastebin link got removed
open a bug report in our discord instead

**Comment by BatmenzDW** [comment]
Don't see a channel for bug reports

**Comment by Sarhadactyl** [comment]
https://discord.com/channels/1094344790910455908/1094368917096497213

**Comment by BatmenzDW** [comment]
Weird, can't see that channel of discord desktop
